name: CI/CD Django

on:
  push:
    branches:
      - main
      - master
      - "**"   # toutes les branches, mais on filtrera par condition
  pull_request:

jobs:
  # -------------------------
  # 1) Compilation + Linting + Tests + Coverage
  # -------------------------
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting with flake8
        run: flake8 .

      - name: Run tests with pytest + coverage
        run: |
          coverage run -m pytest
          coverage report --fail-under=80

  # -------------------------
  # 2) Build & Push Docker image (uniquement sur master/main)
  # -------------------------
  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/python-oc-lettings-fr-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/python-oc-lettings-fr-web:${{ github.sha }}

  # -------------------------
  # 3) Déploiement Render (uniquement sur master/main)
  # -------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
